apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-exporter
  namespace: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-exporter
  template:
    metadata:
      labels:
        app: mongodb-exporter
    spec:
      containers:
        - name: mongodb-exporter
          image: percona/mongodb_exporter:0.40
          ports:
            - containerPort: 9216
          env:
            - name: MONGODB_URI
              value: "mongodb://root:admin@localhost:27017/admin"
